repos:

  # General-purpose hooks (trailing whitespace, EOF fixer, etc.)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files

  # Python code formatting (Black)
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3

  # Import sorting (isort)
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        language_version: python3

  # Notebook formatting (auto-fix)
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      # - id: nbqa-black
      #   additional_dependencies: [black==24.4.2]
      #   args: ["--settings-path=pyproject.toml"]
      - id: nbqa-isort
        additional_dependencies: [isort==5.13.2]
        args: ["--settings-path=pyproject.toml"]

  # # Keep notebooks clean of outputs
  # - repo: https://github.com/kynan/nbstripout
  #   rev: 0.7.1
  #   hooks:
  #     - id: nbstripout
