baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'HelmholtzAI Training Series 2025'

[[menu.primary]]
name = "About"
url = "/about/"
weight = 10

[[menu.primary]]
name = "Docs"
url = "/docs/"
weight = 20




[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false


[params.footer]
copyright = "Copyright Nicholas A. Del Grosso, 2025"

[params.social]
github = "nickdelgrosso/HelmholtzAI-TrainingSeries2025"

[params.docs]
darkMode = true
titleIcon = true
sidebarIcons = true
repoURL = "https://github.com/nickdelgrosso/HelmholtzAI-TrainingSeries2025"
repoBranch = "main"
editPage = true
lastMod = true
toc = true
tocMobile = true
scrollSpy = true
intLinkTooltip = false
extLinkNewTab = true
# logoLinkURL = true  # can be a string, a custom url
